# Generated by Django 5.1.5 on 2025-02-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_rawmaterial_currensy_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='currensy_type',
            new_name='currency_type',
        ),
    ]
