# Generated by Django 5.1.5 on 2025-01-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_rename_balance_type_client_currency_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
