# Generated by Django 5.1.5 on 2025-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_sale_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialhistory',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=20),
        ),
    ]
