# Generated by Django 5.1.5 on 2025-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_rawmaterialhistory_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
    ]
