# Generated by Django 5.1.5 on 2025-02-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_sale_is_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='status',
        ),
    ]
