# Generated by Django 5.1.6 on 2025-02-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_dailywork_creator_rawmaterialhistory_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailywork',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='rawmaterialhistory',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='amount',
        ),
    ]
