# Generated by Django 5.1.6 on 2025-02-27 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_rename_price_dailywork_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.worker')),
            ],
            options={
                'verbose_name': 'Kunlik ish',
                'verbose_name_plural': 'Kunlik ishlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBasketCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_count', to='factory.basket')),
                ('user_daily_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.userdailywork')),
            ],
            options={
                'verbose_name': 'Ishchi savat soni',
                'verbose_name_plural': 'Ishchi savat sonlari ',
            },
        ),
        migrations.DeleteModel(
            name='DailyWork',
        ),
    ]
