# Generated by Django 5.1.5 on 2025-03-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_remove_saleitem_amount_sale_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='currency_type',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
