# Generated by Django 5.1.5 on 2025-03-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_remove_sale_amount_remove_sale_currency_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialhistory',
            name='raw_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.rawmaterial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterialhistory',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RawMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.rawmaterial')),
            ],
            options={
                'verbose_name': 'Xomashyo ishlatilishi ',
                'verbose_name_plural': 'Xomashyo ishlatilishi ',
                'ordering': ['-created_at'],
            },
        ),
    ]
