# Generated by Django 5.1.5 on 2025-03-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0017_rawmaterialusage_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdailywork',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
