# Generated by Django 5.1.5 on 2025-03-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_sale_date_userdailywork_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialhistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
