# Generated by Django 5.1.5 on 2025-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0019_rawmaterialhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
