# Generated by Django 5.1.5 on 2025-03-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0020_supplier_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='price',
        ),
    ]
