# Generated by Django 5.1.5 on 2025-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0022_alter_rawmaterialhistory_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='extra_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
