# Generated by Django 5.1.5 on 2025-03-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_supplier_description_supplier_extra_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
