# Generated by Django 5.1.6 on 2025-03-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0024_salarypayment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawMaterialUsage',
        ),
    ]
