# Generated by Django 5.1.6 on 2025-03-30 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0025_delete_rawmaterialusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='landing',
        ),
        migrations.AddField(
            model_name='basket',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.rawmaterial'),
        ),
    ]
