# Generated by Django 5.1.6 on 2025-03-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0026_remove_worker_debt_remove_worker_landing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialhistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userdailywork',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
