# Generated by Django 5.1.5 on 2025-04-01 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_paydebt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_debt',
        ),
        migrations.AddField(
            model_name='sale',
            name='payed_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paydebt',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
