# Generated by Django 5.1.6 on 2025-04-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0029_remove_sale_is_debt_sale_payed_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='landing',
        ),
    ]
