# Generated by Django 5.1.5 on 2025-01-28 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('extra_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('landing', models.FloatField(blank=True, null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
            ],
            options={
                'verbose_name': 'Shartnoma hamkori ',
                'verbose_name_plural': 'Shartnoma hamkorlari ',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('extra_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('landing', models.FloatField(blank=True, null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchi',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('extra_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('landing', models.FloatField(blank=True, null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
                ('trucks_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ijarachi ',
                'verbose_name_plural': 'Ijarachilar ',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('contract_id', models.CharField(max_length=50)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.contractor')),
            ],
            options={
                'verbose_name': 'Shartnoma ',
                'verbose_name_plural': 'Shartnomalar ',
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='USD', max_length=20)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.driver')),
            ],
            options={
                'verbose_name': 'Haydovchi maoshi ',
                'verbose_name_plural': 'Haydovchilar maoshlari ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('state_number', models.CharField(max_length=20, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('tech_passport', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.tenant')),
            ],
            options={
                'verbose_name': 'Mashina ',
                'verbose_name_plural': 'Mashinalar ',
            },
        ),
        migrations.CreateModel(
            name='TirSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('tir_number', models.CharField(max_length=40, unique=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.contract')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('state_number', models.CharField(max_length=20, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('tech_passport', models.CharField(max_length=20, unique=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.car')),
            ],
            options={
                'verbose_name': 'Tirkama ',
                'verbose_name_plural': 'Tirkamalar ',
            },
        ),
        migrations.CreateModel(
            name='CarExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='USD', max_length=20)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.car')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.trailer')),
            ],
            options={
                'verbose_name': 'Mashina harajati ',
                'verbose_name_plural': 'Mashina harajatlari ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('leaving_amount', models.FloatField(blank=True, null=True)),
                ('leaving_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_amount', models.FloatField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('driver_fee', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('left', 'Yuborilgan'), ('arrived', 'Qaytib kelgan'), ('pending', "To'lov kutilyapti"), ('finished', 'Yakunlangan')], default='new', max_length=50)),
                ('arrival_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_transits', to='logistic.contract')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.car')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.driver')),
                ('leaving_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaving_transits', to='logistic.contract')),
            ],
            options={
                'verbose_name': 'Qatnov ',
                'verbose_name_plural': 'Qatnovlar ',
            },
        ),
        migrations.CreateModel(
            name='TransitExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('transfer_type', models.CharField(choices=[('cash', 'Naqd pul'), ('transfer', "O'tkazma")], default='cash', max_length=20)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='USD', max_length=20)),
                ('transit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.transit')),
            ],
            options={
                'verbose_name': 'Qatnov xarajati ',
                'verbose_name_plural': 'Qatnov xarajatlari ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransitIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('transfer_type', models.CharField(choices=[('cash', 'Naqd pul'), ('transfer', "O'tkazma")], default='cash', max_length=20)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='USD', max_length=20)),
                ('transit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.transit')),
            ],
            options={
                'verbose_name': 'Qatnov kirimi ',
                'verbose_name_plural': 'Qatnov kirimlari ',
                'ordering': ['-created_at'],
            },
        ),
    ]
