# Generated by Django 5.1.5 on 2025-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tirselling',
            options={'ordering': ['-created_at'], 'verbose_name': 'TIR savdosi ', 'verbose_name_plural': 'TIR savdolari '},
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='status',
        ),
        migrations.AddField(
            model_name='transit',
            name='arrival_currency',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='USD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='fee_currency',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='USD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='leaving_currency',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='USD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='remainder',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transitincome',
            name='reason',
            field=models.CharField(choices=[('leaving', 'Ketish uchun'), ('arrival', 'Qaytish uchun'), ('other', 'Boshqa')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transitincome',
            name='transfer_type',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('transfer', "O'tkazma")], default='transfer', max_length=20),
        ),
    ]
