# Generated by Django 5.1.5 on 2025-02-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_tirselling_options_remove_contractor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carexpense',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='USD', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='UZS', max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='UZS', max_length=10),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='USD', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='UZS', max_length=10),
        ),
        migrations.AlterField(
            model_name='transit',
            name='arrival_currency',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transit',
            name='fee_currency',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transit',
            name='leaving_currency',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transitexpense',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='USD', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitincome',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='USD', max_length=20),
        ),
    ]
