# Generated by Django 5.1.6 on 2025-03-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_carexpense_creator_contract_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.tenant'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='axle_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='trailer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transit',
            name='trailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.trailer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('waiting', 'Kutilmoqda'), ('warning', 'Ogohlantirish'), ('accepted', 'Qabul qilingan'), ('given', 'Berib yuborilgan')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
