# Generated by Django 5.1.6 on 2025-03-18 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_contract_amount_contract_tenant_trailer_axle_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contract',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='USD', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='date',
            field=models.DateField(default='2025-03-18', verbose_name='Shartnoma sanasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Faktura raqami'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractor',
            name='inn',
            field=models.CharField(default='00001', max_length=30, verbose_name='INN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='name',
            field=models.CharField(default='Shartnomachi', max_length=100, unique=True, verbose_name='Shartnomachi firma nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(max_length=50, verbose_name='Shartnoma raqami'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='extra_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Qo'shimcha telefon raqami"),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='landing',
            field=models.FloatField(default=0, verbose_name='Qarzdorlik'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Telefon raqami'),
        ),
        migrations.CreateModel(
            name='ContractTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('amount', models.FloatField()),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.contract')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.CharField(max_length=30, verbose_name='TIR raqami')),
                ('get_date', models.DateField(verbose_name='Olish sanasi')),
                ('deadline', models.DateField(verbose_name='Muddati')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('waiting', 'Kutilmoqda'), ('warning', 'Ogohlantirish'), ('accepted', 'Qabul qilingan'), ('given', 'Berib yuborilgan')], default='new', max_length=20, verbose_name='Status')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
