# Generated by Django 5.1.5 on 2025-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_remove_contractor_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tir',
            options={'ordering': ['-created_at'], 'verbose_name': 'TIR ', 'verbose_name_plural': 'TIRlar '},
        ),
        migrations.AddField(
            model_name='contractor',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='UZS', max_length=10, verbose_name='Valyuta turi'),
        ),
        migrations.AlterField(
            model_name='tir',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilingan'), ('given', 'Berib yuborilgan'), ('waiting', 'Kutilmoqda'), ('submitted', 'Topshirilgan')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
