# Generated by Django 5.1.6 on 2025-03-19 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_alter_tir_options_contractor_currency_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TIRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('received_date', models.DateField(verbose_name='TIRni olgan kun')),
                ('submission_deadline', models.DateField(verbose_name='Topshirish muddati')),
                ('is_returned', models.BooleanField(default='False', verbose_name='Holati')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.car', verbose_name='Mashina')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.driver', verbose_name='Haydovchi')),
                ('tir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.tir', verbose_name='TIR')),
                ('trailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.trailer', verbose_name='Tirkama')),
            ],
            options={
                'verbose_name': 'TIR yozuvi ',
                'verbose_name_plural': 'TIR yozuvlari ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TirSelling',
        ),
    ]
