# Generated by Django 5.1.6 on 2025-03-22 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_rename_contract_id_contract_number_contract_car_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('director', models.CharField(blank=True, max_length=100, null=True, verbose_name='Boshliq F.I.O')),
                ('inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='INN')),
                ('xp', models.CharField(blank=True, max_length=30, null=True, verbose_name='XP')),
                ('mfo', models.CharField(blank=True, max_length=30, null=True, verbose_name='MFO')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Kompaniya ',
                'verbose_name_plural': 'Kompaniyalar ',
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='car',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='transitexpense',
            name='transit',
        ),
        migrations.RemoveField(
            model_name='transitincome',
            name='transit',
        ),
        migrations.RemoveField(
            model_name='transitexpense',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='transitincome',
            name='creator',
        ),
        migrations.AlterModelOptions(
            name='contractincome',
            options={'ordering': ['-created_at'], 'verbose_name': "Shartnoma to'lovi ", 'verbose_name_plural': "Shartnoma to'lovlari "},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Haydovchi ', 'verbose_name_plural': 'Haydovchilar '},
        ),
        migrations.RenameField(
            model_name='tirrecord',
            old_name='submission_deadline',
            new_name='tir_deadline',
        ),
        migrations.RenameField(
            model_name='tirrecord',
            old_name='received_date',
            new_name='tir_get_date',
        ),
        migrations.RemoveField(
            model_name='tirrecord',
            name='car',
        ),
        migrations.RemoveField(
            model_name='tirrecord',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='tirrecord',
            name='trailer',
        ),
        migrations.AddField(
            model_name='contractincome',
            name='date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tirrecord',
            name='tir',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.tir', verbose_name='TIR'),
        ),
        migrations.CreateModel(
            name='ContractRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Shartnoma raqami')),
                ('date', models.DateField(verbose_name='Shartnoma sanasi')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Faktura raqami')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='UZS', max_length=20)),
                ('remaining', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('waiting', 'Kutilmoqda'), ('warning', 'Ogohlantirish'), ('accepted', 'Qabul qilingan'), ('given', 'Berib yuborilgan')], default='new', max_length=20, verbose_name='Status')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.contractor')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shartnoma ',
                'verbose_name_plural': 'Shartnomalar ',
            },
        ),
        migrations.CreateModel(
            name='ContractCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.car')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.trailer')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.contractrecord')),
            ],
            options={
                'verbose_name': 'Shartnoma putyovkasi ',
                'verbose_name_plural': 'Shartnoma putyovkalari ',
            },
        ),
        migrations.AlterField(
            model_name='contractincome',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.contractrecord'),
        ),
        migrations.CreateModel(
            name='DriverDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(blank=True, max_length=30, null=True)),
                ('passport', models.CharField(blank=True, max_length=30, null=True)),
                ('given_place', models.CharField(blank=True, max_length=100, null=True)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistic.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.car')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.company')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_1', to='logistic.driver')),
                ('driver_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_2', to='logistic.driver')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.trailer')),
            ],
            options={
                'verbose_name': 'Putyovka ',
                'verbose_name_plural': 'Putyovkalar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tirrecord',
            name='waybill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.waybill', verbose_name='Putyovka '),
        ),
        migrations.DeleteModel(
            name='Transit',
        ),
        migrations.DeleteModel(
            name='TransitExpense',
        ),
        migrations.DeleteModel(
            name='TransitIncome',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
