# Generated by Django 5.1.5 on 2025-03-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_rename_contract_id_contract_number_contract_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tir',
            old_name='number',
            new_name='serial_number',
        ),
    ]
