# Generated by Django 5.1.5 on 2025-03-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0010_company_remove_contract_car_and_more'),
        ('logistic', '0010_rename_number_tir_serial_number'),
    ]

    operations = [
    ]
