# Generated by Django 5.1.5 on 2025-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_merge_20250323_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='landing',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='given_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='given_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='licence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='passport',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='DriverDocuments',
        ),
    ]
