# Generated by Django 5.1.6 on 2025-03-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_remove_driver_debt_remove_driver_landing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carexpense',
            options={'ordering': ['-date'], 'verbose_name': 'Mashina harajati ', 'verbose_name_plural': 'Mashina harajatlari '},
        ),
        migrations.AddField(
            model_name='carexpense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractincome',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tir',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('given', 'Berib yuborilgan'), ('accepted', 'Qabul qilingan'), ('submitted', 'Topshirilgan')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='WaybillPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('amount', models.FloatField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.waybill')),
            ],
            options={
                'verbose_name': "Haydochi yo'l puli ",
                'verbose_name_plural': "Haydochi yo'l pullari ",
                'ordering': ['-created_at'],
            },
        ),
    ]
