# Generated by Django 5.1.6 on 2025-03-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0013_alter_carexpense_options_carexpense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybillpayout',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='waybillpayout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waybillpayout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
