# Generated by Django 5.1.6 on 2025-03-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0014_waybillpayout_currency_type_waybillpayout_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='status',
        ),
    ]
