# Generated by Django 5.1.6 on 2025-03-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0015_remove_car_status_remove_trailer_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='tech_passport',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
