# Generated by Django 5.1.6 on 2025-03-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0016_alter_trailer_tech_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
