# Generated by Django 5.1.6 on 2025-03-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0018_rename_salarypayment_logisticsalarypayment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Shartnoma ', 'verbose_name_plural': 'Shartnomalar '},
        ),
    ]
