# Generated by Django 5.1.6 on 2025-03-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0019_alter_contractrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractincome',
            options={'ordering': ['-date'], 'verbose_name': "Shartnoma to'lovi ", 'verbose_name_plural': "Shartnoma to'lovlari "},
        ),
    ]
