# Generated by Django 5.1.6 on 2025-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0020_alter_contractincome_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tech_passport',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
