# Generated by Django 5.1.5 on 2025-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('version', models.CharField(max_length=64)),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Version history',
                'verbose_name_plural': 'Version histories',
            },
        ),
    ]
