# Generated by Django 5.1.5 on 2025-01-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_section_versionhistory_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
