# Generated by Django 5.1.5 on 2025-01-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi ', 'verbose_name_plural': 'Foydalanuvchilar '},
        ),
    ]
