# Generated by Django 5.1.5 on 2025-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, choices=[('logistic', 'Logistika'), ('fridge', 'Muzlatgich'), ('garden', "Bog'"), ('factory', 'Zavod')], max_length=30, null=True),
        ),
    ]
