# Generated by Django 5.1.5 on 2025-01-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified_user_role_user_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
    ]
