# Generated by Django 5.1.6 on 2025-03-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_section'),
        ('users', '0003_user_currency_type_alter_user_section'),
    ]

    operations = [
    ]
