# Generated by Django 5.1.6 on 2025-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250325_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='USD', max_length=10),
        ),
    ]
