# Generated by Django 5.1.5 on 2025-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
