# Generated by Django 5.1.5 on 2025-01-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, choices=[('logistic', 'Logistika'), ('fridge', 'Muzlatgich'), ('garden', "Bog'"), ('factory', 'Zavod'), ('general', 'Umumiy')], max_length=30, null=True),
        ),
    ]
