# Generated by Django 5.1.5 on 2025-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRemainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name': 'Kunlik qoldiq ',
                'verbose_name_plural': 'Kunlik qoldiqlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='acquaintance',
            name='status',
        ),
    ]
