# Generated by Django 5.1.6 on 2025-03-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_moneycirculation_creator_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyremainder',
            name='status',
        ),
        migrations.AddField(
            model_name='dailyremainder',
            name='type',
            field=models.CharField(choices=[('auto', 'Avtomatik'), ('manual', "Qo'lda")], default='manual', max_length=20),
        ),
    ]
