# Generated by Django 5.1.6 on 2025-03-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_currencyrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Valyutalar kursi ', 'verbose_name_plural': 'Valyutalar kurslari '},
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='updated_at',
        ),
    ]
