# Generated by Django 5.1.6 on 2025-03-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_currencyrate_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
