# Generated by Django 5.1.6 on 2025-03-26 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_currencyrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyremainder',
            name='type',
        ),
        migrations.AddField(
            model_name='dailyremainder',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='UZS', max_length=20),
        ),
        migrations.AddField(
            model_name='transactiontosection',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiontosection',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiontosection',
            name='type',
            field=models.CharField(choices=[('give', 'Berish'), ('get', 'Olish')], max_length=20),
            preserve_default=False,
        ),
    ]
