# Generated by Django 5.1.6 on 2025-04-04 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_dailyremainder_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.FloatField(default=0)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='UZS', max_length=20)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('income', 'Kirim'), ('outcome', 'Chiqim')], max_length=20)),
                ('amount', models.FloatField()),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿'), ('RUB', 'RUB🇷🇺')], default='UZS', max_length=20)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
