# Generated by Django 5.1.6 on 2025-04-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bankaccount_accounthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounthistory',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Bank amaoliyoti', 'verbose_name_plural': 'Bank amaliyotlari'},
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
