# Generated by Django 5.1.6 on 2025-04-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_accounthistory_options_accounthistory_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='reason',
            field=models.CharField(blank=True, choices=[('contact_income', 'Shartnoma puli'), ('tax', 'Soliq'), ('tir', "TIR uchun to'lov"), ('to_cash', 'Naqdlashtirish'), ('other', 'Boshqa')], max_length=100, null=True),
        ),
    ]
