# Generated by Django 5.1.5 on 2025-01-25 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Muzlatgich ',
                'verbose_name_plural': 'Muzlatgichlar ',
            },
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.refrigerator')),
            ],
            options={
                'verbose_name': "Elektr energiya to'lovi ",
                'verbose_name_plural': "Elektr energiyalar to'lovlari ",
            },
        ),
    ]
