# Generated by Django 5.1.5 on 2025-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Muzlatgich ',
                'verbose_name_plural': 'Muzlatgichlar ',
            },
        ),
    ]
