# Generated by Django 5.1.6 on 2025-03-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrigerator',
            name='status',
        ),
    ]
