# Generated by Django 5.1.5 on 2025-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
