# Generated by Django 5.1.5 on 2025-01-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitybill',
            options={'ordering': ['-created_at'], 'verbose_name': "Elektr energiya to'lovi ", 'verbose_name_plural': "Elektr energiyalar to'lovlari "},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.refrigerator')),
            ],
            options={
                'verbose_name': 'Xarajat ',
                'verbose_name_plural': 'Xarajatlar ',
                'ordering': ['-created_at'],
            },
        ),
    ]
