# Generated by Django 5.1.5 on 2025-01-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_alter_electricitybill_options_expense'),
        ('fridge', '0002_electricitybill_is_verified_refrigerator_is_verified'),
    ]

    operations = [
    ]
