# Generated by Django 5.1.5 on 2025-01-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_merge_20250130_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
