# Generated by Django 5.1.5 on 2025-01-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_expense_is_verified'),
        ('main', '0002_alter_acquaintance_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.expense')),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.refrigerator')),
            ],
            options={
                'verbose_name': 'Xarajat ',
                'verbose_name_plural': 'Xarajatlar ',
                'ordering': ['-created_at'],
            },
            bases=('main.expense',),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
