# Generated by Django 5.1.5 on 2025-01-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_fridgeexpense_delete_expense'),
        ('main', '0002_alter_acquaintance_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitybill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='electricitybill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='electricitybill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='electricitybill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='electricitybill',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='electricitybill',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='electricitybill',
            name='expense_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.expense'),
            preserve_default=False,
        ),
    ]
