# Generated by Django 5.1.5 on 2025-01-30 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0006_remove_electricitybill_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeexpense',
            name='refrigerator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.refrigerator'),
        ),
    ]
