# Generated by Django 5.1.5 on 2025-01-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gardener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('extra_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('landing', models.FloatField(blank=True, null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
            ],
            options={
                'verbose_name': "Bog'bon ",
                'verbose_name_plural': "Bog'bonlar ",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GardenExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.expense')),
            ],
            options={
                'verbose_name': 'Chiqim ',
                'verbose_name_plural': 'Chiqimlar ',
                'ordering': ['-created_at'],
                'proxy': False,
            },
            bases=('main.expense',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
            ],
            options={
                'verbose_name': 'Kirim ',
                'verbose_name_plural': 'Kirimlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_verified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
                ('gardener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.gardener')),
            ],
            options={
                'verbose_name': 'Oylik maosh',
                'verbose_name_plural': 'Oylik maoshlar ',
                'ordering': ['-created_at'],
            },
        ),
    ]
