# Generated by Django 5.1.5 on 2025-01-31 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gardener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('extra_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('debt', models.FloatField(blank=True, default=0, null=True)),
                ('landing', models.FloatField(blank=True, null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
            ],
            options={
                'verbose_name': "Bog'bon ",
                'verbose_name_plural': "Bog'bonlar ",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('verified', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
                ('gardener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.gardener')),
            ],
            options={
                'verbose_name': 'Oylik maosh',
                'verbose_name_plural': 'Oylik maoshlar ',
                'ordering': ['-created_at'],
            },
        ),
    ]
