# Generated by Django 5.1.5 on 2025-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
            ],
            options={
                'verbose_name': 'Xarajat ',
                'verbose_name_plural': 'Xarajatlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('currency_type', models.CharField(choices=[('USD', 'USD🇺🇸'), ('UZS', 'UZS🇺🇿')], default='UZS', max_length=10)),
            ],
            options={
                'verbose_name': 'Kirim ',
                'verbose_name_plural': 'Kirimlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oylik maosh', 'verbose_name_plural': 'Oylik maoshlar '},
        ),
    ]
