# Generated by Django 5.1.5 on 2025-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gardener',
            old_name='balance_type',
            new_name='currency_type',
        ),
        migrations.AddField(
            model_name='gardener',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gardener',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gardener',
            name='debt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gardener',
            name='landing',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
