# Generated by Django 5.1.5 on 2025-01-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_expense_income_alter_salarypayment_options'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.expense')),
            ],
            options={
                'proxy': False,
            },
            bases=('main.expense',),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
