# Generated by Django 5.1.5 on 2025-01-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_alter_gardener_balance_alter_gardener_debt'),
        ('main', '0002_alter_acquaintance_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenIncome',
            fields=[
                ('income_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.income')),
            ],
            options={
                'verbose_name': 'Kirim ',
                'verbose_name_plural': 'Kirimlar ',
                'ordering': ['-created_at'],
            },
            bases=('main.income',),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
