# Generated by Django 5.1.6 on 2025-02-26 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_alter_gardener_currency_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments_garden', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
